[2025-06-22 18:25:30,063: INFO: main: Welcome]
[2025-06-22 19:01:09,090: INFO: main: Welcome]
[2025-06-24 13:21:27,679: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 13:21:27,707: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 13:22:23,748: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 13:22:23,750: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 13:22:28,246: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 13:22:28,248: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 13:23:56,226: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 13:23:56,560: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 14:42:33,782: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 14:42:33,821: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 14:55:14,552: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 14:55:14,560: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 14:55:21,280: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 14:55:21,282: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 14:58:22,937: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 14:58:22,946: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 14:59:08,224: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 14:59:08,226: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:06:32,519: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:06:32,525: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:13:30,167: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:14:21,231: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:14:21,234: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:15:59,458: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:15:59,463: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:16:21,879: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:19:26,142: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:19:32,088: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:19:32,092: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:22:48,022: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:22:48,025: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:23:30,503: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:23:30,505: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:24:12,103: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:24:12,106: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:25:04,517: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:25:04,522: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:26:59,068: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:27:02,342: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:28:26,489: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:28:42,238: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:28:42,240: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:29:30,685: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:29:30,808: INFO: common: created directory at: artifacts]
[2025-06-24 15:29:34,986: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:29:34,988: INFO: common: created directory at: artifacts]
[2025-06-24 15:32:11,401: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:32:11,431: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:32:11,435: INFO: common: created directory at: artifacts]
[2025-06-24 15:32:16,892: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:32:16,895: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:32:16,898: INFO: common: created directory at: artifacts]
[2025-06-24 15:32:16,899: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-24 15:32:20,739: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:32:20,742: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:32:20,745: INFO: common: created directory at: artifacts]
[2025-06-24 15:32:20,749: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-24 15:32:24,015: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:32:24,019: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:32:24,022: INFO: common: created directory at: artifacts]
[2025-06-24 15:32:24,024: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-24 15:32:24,030: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 15:32:38,807: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 15:32:48,622: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:32:48,625: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:32:48,627: INFO: common: created directory at: artifacts]
[2025-06-24 15:32:48,630: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-24 15:32:48,634: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 15:32:57,921: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 15:33:08,798: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:33:08,801: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:33:08,804: INFO: common: created directory at: artifacts]
[2025-06-24 15:33:08,807: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-24 15:33:08,809: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 15:33:29,665: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 15:34:20,566: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-24 15:34:20,569: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-24 15:34:20,571: INFO: common: created directory at: artifacts]
[2025-06-24 15:34:20,572: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-24 15:34:20,574: INFO: 2934408803: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 15:34:28,299: INFO: 2934408803: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 15:34:29,848: INFO: 2934408803: Extracted zip file sucessfully]
[2025-06-24 22:51:02,148: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<<]
[2025-06-24 22:51:02,251: INFO: common: created directory at: artifacts]
[2025-06-24 22:51:02,264: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-24 22:51:02,265: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 23:00:43,717: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-24 23:00:46,937: INFO: data_ingestion: Extracted zip file sucessfully]
[2025-06-24 23:00:46,939: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-25 12:55:58,878: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-06-25 13:07:33,287: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 13:07:33,408: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 13:07:33,432: INFO: common: created directory at: artifacts]
[2025-06-25 13:07:33,505: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-25 13:10:05,769: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 13:10:05,773: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 13:10:05,776: INFO: common: created directory at: artifacts]
[2025-06-25 13:10:05,778: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-25 13:10:10,030: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 13:10:10,034: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 13:10:10,036: INFO: common: created directory at: artifacts]
[2025-06-25 13:10:10,038: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-25 13:10:37,496: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 13:10:37,500: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 13:10:37,502: INFO: common: created directory at: artifacts]
[2025-06-25 13:10:37,504: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-25 13:12:04,137: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 13:12:04,140: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 13:12:04,143: INFO: common: created directory at: artifacts]
[2025-06-25 13:12:04,144: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-25 13:12:20,055: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 13:12:20,058: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 13:12:20,061: INFO: common: created directory at: artifacts]
[2025-06-25 13:12:20,062: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-25 13:12:44,133: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 13:12:44,137: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 13:12:44,141: INFO: common: created directory at: artifacts]
[2025-06-25 13:12:44,143: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-25 13:14:29,455: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 13:14:29,515: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 13:14:29,517: INFO: common: created directory at: artifacts]
[2025-06-25 13:14:29,520: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-25 13:14:42,974: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-06-25 13:14:44,009: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-06-25 13:39:58,285: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-06-25 13:40:02,246: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<<]
[2025-06-25 13:40:02,346: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 13:40:02,351: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 13:40:02,353: INFO: common: created directory at: artifacts]
[2025-06-25 13:40:02,353: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-25 13:40:02,354: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-25 13:40:13,733: ERROR: main: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001EC1D3825D0>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))]
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\Lib\site-packages\urllib3\connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "C:\Users\hp\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\Users\hp\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Users\hp\anaconda3\Lib\site-packages\urllib3\connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\urllib3\connection.py", line 206, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001EC1D3825D0>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001EC1D3825D0>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\learnbay\DL PROjECTS\Kidney-Disease-Classification-MLflow-DVC\main.py", line 9, in <module>
    obj.main()
  File "D:\learnbay\DL PROjECTS\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\pipeline\stage_01_data_injestion.py", line 15, in main
    data_ingestion.download_file()
  File "D:\learnbay\DL PROjECTS\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\components\data_ingestion.py", line 31, in download_file
    raise e
  File "D:\learnbay\DL PROjECTS\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\components\data_ingestion.py", line 26, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\hp\anaconda3\Lib\site-packages\gdown\download.py", line 202, in download
    res = sess.get(url, stream=True, verify=verify)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\anaconda3\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001EC1D3825D0>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))
[2025-06-25 14:20:56,238: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-06-25 14:21:00,269: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<<]
[2025-06-25 14:21:00,271: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 14:21:00,274: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 14:21:00,275: INFO: common: created directory at: artifacts]
[2025-06-25 14:21:00,275: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-25 14:21:00,276: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-25 14:21:10,401: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-25 14:21:15,103: INFO: data_ingestion: Extracted zip file sucessfully]
[2025-06-25 14:21:15,105: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-25 14:21:15,106: INFO: main: *******************]
[2025-06-25 14:21:15,106: INFO: main: >>>>>> stage Base model preparation stage started <<<<<<]
[2025-06-25 14:21:15,110: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 14:21:15,113: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 14:21:15,114: INFO: common: created directory at: artifacts]
[2025-06-25 14:21:15,115: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-25 14:21:16,234: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-06-25 14:21:17,355: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-06-25 14:21:18,338: INFO: main: >>>>>> stage Base model preparation stage completed <<<<<<

x==========x]
[2025-06-25 14:38:40,327: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-06-25 14:38:43,714: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<<]
[2025-06-25 14:38:43,717: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 14:38:43,720: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 14:38:43,721: INFO: common: created directory at: artifacts]
[2025-06-25 14:38:43,722: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-25 14:38:43,722: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-25 14:38:53,766: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-06-25 14:38:56,679: INFO: data_ingestion: Extracted zip file sucessfully]
[2025-06-25 14:38:56,680: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-25 14:38:56,681: INFO: main: *******************]
[2025-06-25 14:38:56,682: INFO: main: >>>>>> stage Base model preparation stage started <<<<<<]
[2025-06-25 14:38:56,688: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-25 14:38:56,695: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-25 14:38:56,697: INFO: common: created directory at: artifacts]
[2025-06-25 14:38:56,699: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-25 14:38:58,126: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-06-25 14:39:04,024: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-06-25 14:39:05,406: INFO: main: >>>>>> stage Base model preparation stage completed <<<<<<

x==========x]
